# Site settings
title: MrKnight
email: lei.huang@pku.edu.cn
description: "Just on the road~~"
baseurl: ""
url: ""
encoding: utf-8

def_categories_cn: [编程杂事, 算法积累, 生活点滴, 就业工作]
def_categories_en: [coding, algorithm, life, job]
categories_path : category

author:
 name: Huang Lei
 email: hhuangllei@qq.com
 github_username:  hhuangllei
 weibo_username: hhuangllei
 
# default Markdown interpreter: Maruku, upgrading to kramdown
# Build settings
markdown: kramdown
permalink: pretty
highlighter: pygments
excerpt_separator: ""

paginate: 10
paginate_path: "page:num"